### ISSUE TITLE
Expo env changes for development and production

### ISSUE THREAD

**Issue by Zappi** [luomus/mobile-vihko-app#16]

**Comment by rpulkka** [comment]
Options for being able to build the app with dev and prod env variables were investigated and we ended up using a method where we have .env and prod.env -files and their content is pushed to EAS before each build. This has now been documented to the project's README, no coding required. Closing the issue. Here's a link to the method that we use to push the env variables: https://docs.expo.dev/build-reference/variables/#importing-secrets-from-a-dotenv-file
