### ISSUE TITLE
Create new releases of Mobiilivihko based on Expo 51 and Redux Toolkit

### ISSUE THREAD

**Issue by wkmor1** [luomus/mobile-vihko-app#33]
This Epic is about refactoring Mobiilivihko to use Expo 51 and Redux Toolkit. Releases that need approval have been added as sub-tasks.

(October 1, 2024) Progressing on the sending the documents. Next is to edit the document

**Comment by rpulkka** [comment]
Now editing works, tracking features work. Started using "development builds" instead of "expo go" for developing the app. There's still some unreliable thunk actions, trying to get this sorted asap.

**Comment by rpulkka** [comment]
Test version 1.5.10 has been released for Android, today I'll release also the iOS test version.
