### ISSUE TITLE
Release Mobiilivihko Android after Redux refactoring

### ISSUE THREAD

**Issue by rpulkka** [luomus/mobile-vihko-app#34]
Release a functioning Android version of Mobiilivihko after Redux refactoring changes.

Definition of needs approval: App released as beta on Google Play
Definition of approved: PO reports that the beta version works as expected
Definition of done: App released to prod on Google Play

**Comment by rpulkka** [comment]
Test version 1.5.10 has been released for Android, today I'll release also the iOS test version.

**Comment by wkmor1** [comment]
@rpulkka should this have status "Needs Approval" if points 3 & 4 have not happened yet?

**Comment by rpulkka** [comment]
@wkmor1 Fair enough. Maybe I shouldn't have included the deployment to the points, so it wouldn't need "approval" from the tester/PO before the status technically goes to "needs approval". But this can be fixed by setting the status to "in progress" and notifying Mikko that the app can be tested now (done on Slack).

**Comment by wkmor1** [comment]
Yeah up to you how to formulate the tasks. Just need to make sure it is clear to the owner what they are approving. Perhaps this task could be split into few tasks? Its hard at them moment to understand how it is different from its parent Epic?

**Comment by mikkohei13** [comment]
Tested with Android. Trip form and single observation form work ok, also with images. Loading species lists for atlas & complete lists fail.

**Comment by rpulkka** [comment]
@mikkohei13 Should work now. Atlas-API address pointed to old Rahti. This issue has been breaking Atlas + Biomon forms on production for two days now. We should publish an update as soon as basic functionality of the app has been confirmed.

**Comment by mikkohei13** [comment]
Tested bird atlas & dragonfly complete list forms. Both work ok.
