### ISSUE TITLE
Release Mobiilivihko iOS after Redux refactoring

### ISSUE THREAD

**Issue by rpulkka** [luomus/mobile-vihko-app#35]
Release a functioning iOS version of Mobiilivihko after Redux refactoring changes.

Definition of needs approval: App released as beta on App Store
Definition of approved: PO reports that the beta version works as expected
Definition of done: App released to prod on App Store

**Comment by rpulkka** [comment]
I tested this today outdoors and it worked.

@mikkohei13 Can you test 1.5.11 on iOS (test flight)? @wkmor1 You can also test if interested.

**Comment by wkmor1** [comment]
Sure. Will try and take a look over the weekend

**Comment by mikkohei13** [comment]
Tested the trip form iPhone 8 / iOS 16.3: works ok.
